### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by vit1251** [andersbll/neural_artistic_style#7] opened 2015-09-04 01:36 UTC
``` bash
CUDArray: CUDA back-end not available, using NumPy.
Traceback (most recent call last):
  File "./neural_artistic_style.py", line 112, in <module>
    run()
  File "./neural_artistic_style.py", line 104, in run
    cost = np.mean(net._update())
  File "C:\WORK\py\netral\neural_artistic_style\style_network.py", line 149, in _update
    grad = layer.bprop(grad)
  File "C:\WORK\py\netral\neural_artistic_style\style_network.py", line 26, in bprop
    to_imgs=True, to_filters=False
  File "C:\Python27\lib\site-packages\cudarray-0.1.dev0-py2.7-win32.egg\cudarray\numpy_backend\nnet\conv.py", line 37, in bprop
    b, c, _, _ = imgs.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by andersbll** [comment] 2015-09-04 12:07
Duplicate of #5. Will be fixed in two seconds! :)

**Closed as completed by andersbll** 2015-09-04 12:07 UTC
