### ISSUE TITLE
TypeError: float() argument must be a string or a number

### ISSUE THREAD

**Issue by anatolyburtsev** [andersbll/neural_artistic_style#9] opened 2015-09-04 15:56 UTC
Hello! 
I tried to run it without CUDA and this error occured

python neural_artistic_style.py --subject images/tuebingen.jpg --style images/starry_night.jpg
CUDArray: CUDA back-end not available, using NumPy.
Traceback (most recent call last):
  File "neural_artistic_style.py", line 140, in <module>
    run()
  File "neural_artistic_style.py", line 103, in run
    style_img = imread(args.style) - pixel_mean
  File "neural_artistic_style.py", line 39, in imread
    return scipy.misc.imread(path).astype(dp.float_)
TypeError: float() argument must be a string or a number

pip list
cudarray (0.1.dev0)
Cython (0.23.1)
deeppy (0.1.dev0)
numpy (1.9.2)
Pillow (2.9.0)
pip (7.1.2)
scipy (0.16.0)
setuptools (17.0)
wheel (0.24.0)

**Comment by andersbll** [comment] 2015-09-04 16:00
Duplicate of #8.

**Closed as completed by andersbll** 2015-09-04 16:00 UTC
