### ISSUE TITLE
Numpy backend doesn't support None as an input

### ISSUE THREAD

**Issue by yinghai** [andersbll/neural_artistic_style#10] opened 2015-09-04 20:13 UTC
File "/cudarray/numpy_backend/nnet/conv.py", line 37, in bprop b, c, _, _ = imgs.shape AttributeError: 'NoneType' object has no attribute 'shape'

From style_network.py:26

**Comment by andersbll** [comment] 2015-09-04 20:48
Duplicate of #5.

**Closed as completed by andersbll** 2015-09-04 20:48 UTC
